"""
10-Q Equity Research Agent -- Streamlit entrypoint.

Enter any US-listed ticker -> pulls its latest real 10-Q from SEC EDGAR
(free, public, no key) -> computes standardized financial ratios from the
filing's actual XBRL data -> runs a 5-step LLM analysis pipeline
(services/pipeline.py) -> renders a quantitative snapshot, risk synthesis,
and a final equity research stance.

Run locally:   streamlit run app.py
Deploy free:   https://share.streamlit.io, pointed at this repo, app.py as
               the entrypoint, GEMINI_API_KEY set in the app's Secrets.
"""

import streamlit as st

from core import edgar_client, ratios as ratios_mod
from services.pipeline import run_analysis

st.set_page_config(page_title="10-Q Equity Research Agent", page_icon="\U0001F4C8", layout="wide")

st.title("10-Q Equity Research Agent")
st.caption(
    "Enter a ticker to pull its real, latest 10-Q from SEC EDGAR and run a 5-step "
    "research pipeline against it. Educational demo -- not investment advice."
)

ticker = st.text_input("Ticker", placeholder="e.g. AAPL, MSFT, JPM").strip().upper()
run_clicked = st.button("Run analysis", type="primary", disabled=not ticker)

if run_clicked and ticker:
    with st.spinner(f"Looking up {ticker} on SEC EDGAR..."):
        filing = edgar_client.latest_10q(ticker)

    if filing is None:
        st.error(
            f"No 10-Q found for '{ticker}' on SEC EDGAR. Check the ticker is a "
            "US-listed filer (foreign private issuers file 6-K/20-F instead of 10-Q)."
        )
        st.stop()

    st.success(f"Found: {filing.company_name} -- 10-Q for period ending {filing.report_date}, "
               f"filed {filing.filing_date}. [View filing on SEC.gov]({filing.document_url})")

    with st.spinner("Fetching XBRL financials..."):
        facts_json = edgar_client.company_facts(filing.cik)
        facts = ratios_mod.extract_facts(facts_json)
        computed = ratios_mod.compute_ratios(facts)

    with st.expander("Computed financial ratios (from this filing's real XBRL data)", expanded=True):
        for section, values in computed.items():
            if section == "data_gaps":
                continue
            st.markdown(f"**{section.replace('_', ' ').title()}**")
            st.table({k: (f"{v:.2%}" if isinstance(v, float) and abs(v) < 3 else v) for k, v in values.items()})
        if computed.get("data_gaps"):
            st.caption(f"Not tagged in this filing's XBRL data: {', '.join(computed['data_gaps'])}")

    with st.spinner("Fetching filing text for MD&A / risk factors..."):
        filing_text = edgar_client.fetch_filing_text(filing)

    with st.spinner("Running 5-step analysis pipeline (this calls a free-tier LLM 5 times, may take a minute)..."):
        try:
            run = run_analysis(filing.company_name, ticker, filing.report_date, computed, filing_text)
        except RuntimeError as exc:
            st.error(str(exc))
            st.stop()

    st.header("Analysis")
    for step in run.steps:
        with st.expander(step.title, expanded=False):
            st.markdown(step.output)

    st.header("Equity Research Stance")
    st.markdown(run.recommendation)

    st.caption(
        "Generated by a 5-step LLM pipeline grounded in this filing's real SEC XBRL data and "
        "filing text. Educational demo only -- not investment advice."
    )
